### ISSUE TITLE
Drop-Down not showing any selection

### ISSUE THREAD

**Issue by jeretc** [MissVeronica/um-three-way-dropdowns#1]
Hello, I have installed and activated the plugin. Copied the dropdowns.csv file to my active themes folder in threewaydropdowns folder. Then added this in the drop down:

Callback dropdown top level: get_custom_top_list_dropdown
Callback dropdown mid level: get_custom_mid_list_dropdown
Callback dropdown bottom level: get_custom_btm_list_dropdown

In the drop down nothing shows up for all the 3 drop downs.

![image](https://github.com/MissVeronica/um-three-way-dropdowns/assets/20941239/aff95446-dec5-48be-9913-68d4d75d4d99)

**Comment by MissVeronica** [comment]
No, the dropdowns.csv must be in the uploads folder, where you create a new folder: threewaydropdowns.
 .../wp-content/uploads/ultimatemember/threewaydropdowns/

**Comment by jeretc** [comment]
Noted. Thanks
