### ISSUE TITLE
How to use the plugin

### ISSUE THREAD

**Issue by jerrybarry** [MissVeronica/um-three-way-dropdowns#2]
After installing the plugin, I went to the Dropdown A and selected the Category and added some Lines to test and save changes. Now I've this [error](https://imgur.com/a/NNQaQwI).

**Comment by MissVeronica** [comment]
You must enter columns names from the spreadsheet like A B C

**Comment by jerrybarry** [comment]
Can I do this without using Spreadsheet? Also, can I use the plugin without spreadsheet.

**Comment by jerrybarry** [comment]
I've this fields already registered. 

{
    "Technology": [
        "Hotel Software PMS",
        "Guest Experience",
        "Digital Solutions"
    ],
    "Food & Beverage": [
        "Vendors & Suppliers",
        "F&B apps",
        "F&B Consultant",
        "Fresh Farm"
    ],
    "Legal, HR, Insurance": [
        "Legal services",
        "HR services",
        "Insurance services"
    ],
    "Sustainability": [
        "Sustainability Solutions",
        "Eco Hotel Supplies"
    ],
    "General Hotel Supplies": [
        "Hotel amenities",
        "Hotel Linen & Towels",
        "Furniture",
        "Equipment",
        "Uniforms"
    ],
    "Fitness & Wellness": [
        "Fitness & Wellness services",
        "Consultants"
    ],
    "Design": [
        "Interior Designers",
        "Architects",
        "Photographers",
        "Deco Vendors & Suppliers"
    ],
    "Development, Management, Real Estate": [
        "Real Estate Consultants",
        "Hotel Management Companies",
        "Construction"
    ],
    "Marketing, PR, Creative Solutions": [
        "PR Services",
        "Marketing Agencies"
    ],
    "Experience Design": [
        "Art Curators",
        "WoW Services",
        "Other experiences"
    ],
    "Consultants – Advisors": [
        "Consulting services"
    ],
    "Various other solutions": [
        "Housekeeping Facilities",
        "Outsourced Services",
        "Transfers and Pickups"
    ],
    "Partner with Individual artists": [
        "Art Curator",
        "Art Consultant"
    ],
    "Travel": [
        "Travel Agencies",
        "Travel Consortium",
        "Luxury Concierge Agencies"
    ],
    "Hotels": [
        "Hotels"
    ]
}

How can add to this list? I have the category fields with meta key as "custom_category" which is the parent and the subcategory as custom_subacategories

**Comment by MissVeronica** [comment]
I will look at your Format and compare it to the cache file being created from the spreadsheet.

**Comment by jerrybarry** [comment]
Okay! Please write back to me when you have that ready. And also write to me how I can use the plugin with the data I have already.

**Comment by jerrybarry** [comment]
@MissVeronica I havn't heard from you

**Comment by MissVeronica** [comment]
I'm still working with the plugin.
Ready with a conversion of your file to .csv format to include the data into the plugin.
Remaining issues are with the changes I have to do for the new version 3.2.0

**Comment by jerrybarry** [comment]
Okay! Thank you. 

And also, can we make it a two-way to update the dropdown fields; through .csv format and also writing them out.

**Comment by MissVeronica** [comment]
Version 3.2.0 is now available for download. Read documentation about the text file option.
https://github.com/MissVeronica/um-three-way-dropdowns

Dropdown options cache is updated from current uploaded .txt or .csv files in the folder each time you click at one of the sublinks in UM Settings -> Dropdowns

**Comment by jerrybarry** [comment]
@MissVeronica Thank you very much! You are sucha lifesaver

**Comment by MissVeronica** [comment]
I have added an Imgur image of my settings ** Link removed **

**Comment by jerrybarry** [comment]
@MissVeronica For me to add the **level** and **sub_level**, do I need to add the .csv file? Or is there a way I can add text first for each **level** to its **sub_level** directly?.

**Comment by jerrybarry** [comment]
I got this when I saved your csv file to rest https://imgur.com/a/tAycnKy

**Comment by MissVeronica** [comment]
You upload with your FTP client either the text file or the .CSV file to this folder:
`.../wp-content/uploads/ultimatemember/threewaydropdowns/`

You can't split the the files into two because top and sublevel depend on each other.
The option for entering several input files are for large number of entries like different countries where you have country, region,cities then you can have one file per country.

**Comment by jerrybarry** [comment]
for my own scenerio as such, how do I make the file? I have just the category and subcategory dropdown.

{
"Technology": [
"Hotel Software PMS",
"Guest Experience",
"Digital Solutions"
],
"Food & Beverage": [
"Vendors & Suppliers",
"F&B apps",
"F&B Consultant",
"Fresh Farm"
],
"Legal, HR, Insurance": [
"Legal services",
"HR services",
"Insurance services"
],
"Sustainability": [
"Sustainability Solutions",
"Eco Hotel Supplies"
],
"General Hotel Supplies": [
"Hotel amenities",
"Hotel Linen & Towels",
"Furniture",
"Equipment",
"Uniforms"
],
"Fitness & Wellness": [
"Fitness & Wellness services",
"Consultants"
],
"Design": [
"Interior Designers",
"Architects",
"Photographers",
"Deco Vendors & Suppliers"
],
"Development, Management, Real Estate": [
"Real Estate Consultants",
"Hotel Management Companies",
"Construction"
],
"Marketing, PR, Creative Solutions": [
"PR Services",
"Marketing Agencies"
],
"Experience Design": [
"Art Curators",
"WoW Services",
"Other experiences"
],
"Consultants – Advisors": [
"Consulting services"
],
"Various other solutions": [
"Housekeeping Facilities",
"Outsourced Services",
"Transfers and Pickups"
],
"Partner with Individual artists": [
"Art Curator",
"Art Consultant"
],
"Travel": [
"Travel Agencies",
"Travel Consortium",
"Luxury Concierge Agencies"
],
"Hotels": [
"Hotels"
]
}

**Comment by jerrybarry** [comment]
I successfully installed the file and fields of your sample file that is inside your plugin's folder directory (dropdown.csv) but the issue now is that the fields are not shown on the profile form and member directory where I use them.

See here https://imgur.com/a/8SWMEMG

**Comment by MissVeronica** [comment]
Create a .TXT file with this content on your PC.
Create the folder `threewaydropdowns` in this folder `.../wp-content/uploads/ultimatemember/` with your FTP client or cPanel FileManager.
Upload the .TXT file with your FTP client to this new folder `.../wp-content/uploads/ultimatemember/threewaydropdowns/`
UM Settings -> Dropdowns -> Dropdown will now convert your .TXT file to a `filename.txt.csv` file to be used by the plugin
Enter the `filename.txt.csv` in the field "CSV File Names (one name per line) "

**Comment by jerrybarry** [comment]
You mean, one name per line? Help me understand because I have level and sub_level fields now can I make them.

Formally, I used to call the fields using the codes on Ultimate Members documentation (choice callback codes)

Is there a way to automate the fields to be shown without codes?

Sorry for the too many questions.

**Comment by MissVeronica** [comment]
Upload your .TXT file instead of my test file

**Comment by jerrybarry** [comment]
I uploaded my own file and this is what I got but fields doesn't show on my profile forms https://imgur.com/a/Twe6ySP

**Comment by MissVeronica** [comment]
This format is A and C

**Comment by jerrybarry** [comment]
Thank you!

But the added fields are not showing on the profile forms and members directory.

**Comment by MissVeronica** [comment]
Fields are shown when there is User data saved to the fields.

**Comment by jerrybarry** [comment]
Okay. On the profile form, they don't display yet https://imgur.com/a/PHvU658

**Comment by jerrybarry** [comment]
Also, maybe give me a guide to follow on how I can add the dropdown fields. This might be the reason they're not showing

**Comment by MissVeronica** [comment]
Show me your settings in UM Forms Builder for the fields Category and Sub Category

**Comment by jerrybarry** [comment]
Here you go https://imgur.com/a/3glFrSY

**Comment by MissVeronica** [comment]
You have not changed your old callbacks

From the plugin's UM Settings -> Dropdowns -> Dropdown very first lines on the page these callbacks are:

```
UM Forms Dropdown Callbacks:
Top level: "get_custom_top_list_dropdown"
Middle level: "get_custom_mid_list_dropdown"
```

**Comment by jerrybarry** [comment]
@MissVeronica 

Thank you very much for this.
Worked just very well.

**Comment by jerrybarry** [comment]
@MissVeronica 
Sorry to have asked. The dropdown filters for my subcategories field are not shown on Members Directory.

**Comment by MissVeronica** [comment]
OK
I will look at this issue later. I don't think that the conditions are implemented in the Members Directory.
Please show some screen copies of your settings and what you get in the Members Directory page.

**Comment by jerrybarry** [comment]
Thank you for your responses. Here are the screen copies of my settings and what shows on the Members Directory Page. https://imgur.com/a/Rr9n90w

**Comment by MissVeronica** [comment]
Thanks for the screen copies.

Here is a status update:
I have changed some coding now so I can get response from the mid dropdown for some values not all selections in the top dropdown.

When I click the mid selection the Directory should show the Profile with these two values but nothing is displayed.

**Comment by jerrybarry** [comment]
Okay! Thanks, can I install the update?

**Comment by jerrybarry** [comment]
@MissVeronica 
Hi, any update?

**Comment by MissVeronica** [comment]
Version 3.2.1 Code improvements for Members Directory

**Comment by jerrybarry** [comment]
@MissVeronica Thank you so much. This worked, just so well.

**Comment by jerrybarry** [comment]
The issue now here is that, the subcat fields are showing all fields selected by the users, it is not getting generic fields from the cat and then filter to get the subcat.

This needs to be looked into.

Great job, btw

**Comment by MissVeronica** [comment]
This is the request from the Javascript at the PC  when there are two selections
```
Array
(
    [directory_id] => 5c0c6
    [page] => 1
    [search] => 
    [sorting] => username
    [gmt_offset] => 2
    [post_refferer] => 1044
    [nonce] => 66c907c83d
    [three_top] => Array
        (
            [0] => Technology 1
            [1] => Technology 2
        )

    [three_mid] => Array
        (
            [0] => Digital Solutions
            [1] => Hotel Software PMS 2
        )

    [action] => um_get_members
)
```

and UM is searching for the users by this SQL logic

Find users which have:
three_top meta_value like "Technology 1" OR "Technology 2"
AND
three_mid meta_value like "Digital Solutions" OR "Hotel Software PMS 2"

**Comment by jerrybarry** [comment]
@MissVeronica How do we then solve this?

**Comment by jerrybarry** [comment]
@MissVeronica I've been trying to work the plugin myself to achieve the mid-level to show dropdown base on the top-level, but still haven't been able to get it right.

Any update from your end? :)

**Comment by jerrybarry** [comment]
@MissVeronica Hi

Any update with the bug?

**Comment by MissVeronica** [comment]
I will look at this issue during this week.
An update will be available by the end of the week.

**Comment by jerrybarry** [comment]
Alright! I'll be waiting you hear from you then.

Thank you so much @MissVeronica

**Comment by MissVeronica** [comment]
There is an update version 3.2.2 available for download now.

Still one issue with "Clear all" which will leave options in the mid dropdown if top selection is made for more than one option. Removing options from the selection list one by one will work OK.

Possible fix is to remove "Clear all" with this CSS added to WP Appearance -> Customize -> CSS
```
.um-clear-filters a {
  display: none !important;
}
```
"Clear all" is an UM Javascript bug which I will report.

**Comment by MissVeronica** [comment]
I had to update the plugin to version 3.2.3 after testing a Registration 
where all Registration fields were logged by the plugin.

**Comment by jerrybarry** [comment]
@MissVeronica Thank you very much. 

I'll try it out and let you know how it work.

Thank you once more

**Comment by MissVeronica** [comment]
I have made an UM bug report about the "Clear all" issue now
https://github.com/ultimatemember/ultimatemember/issues/1526

**Comment by jerrybarry** [comment]
Thank you so much Veronica!

Plugin works as excepted. I did the temporal fix for "clear all" until UM fixes the bug.

**Comment by MissVeronica** [comment]
I have noticed a minor issue today.
UM is getting all values for the dropdowns and if you have users either awaiting email confirmation or admin review  their selected dropdown values are also included in the pre-read.
This will give "No users found" if the dropdown value is not selected by any other user.

**Comment by jerrybarry** [comment]
Great, you noticed that also.

Caught that too today, but I used some codes to make all list for top level dropdown to be shown in the directory, which solved the issue for now.
Was hoping report that to you today :) 


Also, if you've got the time, I need your help with a bug on um not relating to this rather.

Thank you!

**Comment by jerrybarry** [comment]
Hi @MissVeronica 

How can I make all the fields of top level show in members directory even if they're selected by members?

**Comment by jerrybarry** [comment]
I did this to display them dynamically and it seem to work just fine.

add_filter("um_member_directory_filter_select_options", "custom_display_custom_category_options", 10, 3);
function custom_display_custom_category_options($options, $values_array, $attrs) {
    if (isset($attrs['metakey']) && 'custom_category' == $attrs['metakey']) {
        // Use the callback function to get the custom categories
        $custom_categories = get_custom_top_list_dropdown();

        // Add each custom category to the options
        foreach ($custom_categories as $key => $category) {
            $options[$key] = $category;
        }
    }

    return $options;
}

**Comment by MissVeronica** [comment]
Yes that's right hook to use.
Updated plugin to version 3.2.4 works for all dropdowns supported by the plugin and optional sorting of the keys.
https://github.com/MissVeronica/um-three-way-dropdowns

**Comment by jerrybarry** [comment]
@MissVeronica Thank you, I will do well to check it out.

**Comment by MissVeronica** [comment]
The "Clear all" issue is addressed for next version of UM
https://github.com/ultimatemember/ultimatemember/pull/1538

**Comment by jerrybarry** [comment]
@MissVeronica Thank you so much!
